package clases;
// Generated 18 ene 2023 15:43:24 by Hibernate Tools 3.5.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "empleados23")
public class Departamento implements java.io.Serializable {

	private Integer numDepto;
	private String nombre;
	private String localidad;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Departamento() {
	}

	public Departamento(String nombre, String localidad, Set<Empleado> empleados) {
		this.nombre = nombre;
		this.localidad = localidad;
		this.empleados = empleados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "numDepto", unique = true, nullable = false)
	public Integer getNumDepto() {
		return this.numDepto;
	}

	public void setNumDepto(Integer numDepto) {
		this.numDepto = numDepto;
	}

	@Column(name = "nombre", length = 15)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "localidad", length = 15)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
