package clases;
// Generated 18 ene 2023 15:43:24 by Hibernate Tools 3.5.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", catalog = "empleados23")
public class Empleado implements java.io.Serializable {

	private int numEmpleado;
	private Departamento departamento;
	private String nombre;
	private String apellido;
	private Date fechaAlta;
	private BigDecimal salario;

	public Empleado() {
	}

	public Empleado(int numEmpleado, Departamento departamento) {
		this.numEmpleado = numEmpleado;
		this.departamento = departamento;
	}

	public Empleado(int numEmpleado, Departamento departamento, String nombre, String apellido, Date fechaAlta,
			BigDecimal salario) {
		this.numEmpleado = numEmpleado;
		this.departamento = departamento;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaAlta = fechaAlta;
		this.salario = salario;
	}

	@Id

	@Column(name = "numEmpleado", unique = true, nullable = false)
	public int getNumEmpleado() {
		return this.numEmpleado;
	}

	public void setNumEmpleado(int numEmpleado) {
		this.numEmpleado = numEmpleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numDepto", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "nombre", length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 25)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaAlta", length = 10)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "salario", precision = 6)
	public BigDecimal getSalario() {
		return this.salario;
	}

	public void setSalario(BigDecimal salario) {
		this.salario = salario;
	}

}
